In [78]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import math
import warnings
warnings.filterwarnings( "ignore" )

col_names = ['x1','x2','result']
#load dataset
df = pd.read_csv("Student-University.csv", names=col_names)
print(df)


           x1         x2  result
0   34.623660  78.024693       0
1   30.286711  43.894998       0
2   35.847409  72.902198       0
3   60.182599  86.308552       1
4   79.032736  75.344376       1
..        ...        ...     ...
95  83.489163  48.380286       1
96  42.261701  87.103851       1
97  99.315009  68.775409       1
98  55.340018  64.931938       1
99  74.775893  89.529813       1

[100 rows x 3 columns]


In [79]:
X = df.iloc[:,:-1].values
print(X)

[[34.62365962 78.02469282]
 [30.28671077 43.89499752]
 [35.84740877 72.90219803]
 [60.18259939 86.3085521 ]
 [79.03273605 75.34437644]
 [45.08327748 56.31637178]
 [61.10666454 96.51142588]
 [75.02474557 46.55401354]
 [76.0987867  87.42056972]
 [84.43281996 43.53339331]
 [95.86155507 38.22527806]
 [75.01365839 30.60326323]
 [82.30705337 76.4819633 ]
 [69.36458876 97.71869196]
 [39.53833914 76.03681085]
 [53.97105215 89.20735014]
 [69.07014406 52.74046973]
 [67.94685548 46.67857411]
 [70.66150955 92.92713789]
 [76.97878373 47.57596365]
 [67.37202755 42.83843832]
 [89.67677575 65.79936593]
 [50.53478829 48.85581153]
 [34.21206098 44.2095286 ]
 [77.92409145 68.97235999]
 [62.27101367 69.95445795]
 [80.19018075 44.82162893]
 [93.1143888  38.80067034]
 [61.83020602 50.25610789]
 [38.7858038  64.99568096]
 [61.37928945 72.80788731]
 [85.40451939 57.05198398]
 [52.10797973 63.12762377]
 [52.04540477 69.43286012]
 [40.23689374 71.16774802]
 [54.63510555 52.21388588]
 [33.91550011 98.86943574]
 

In [80]:
Y = df.iloc[:,-1:].values
print(Y)

[[0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [81]:
# Splitting dataset into train and test set
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 1/3, random_state = 0)

In [82]:
x1 = X_train[:,0]

In [83]:
x1

array([99.27252693, 93.1143888 , 70.66150955, 97.64563396, 30.05882245,
       58.84095622, 30.28671077, 35.28611282, 94.44336777, 51.54772027,
       79.03273605, 53.97105215, 67.94685548, 83.90239366, 74.78925296,
       45.08327748, 90.44855097, 71.79646206, 34.62365962, 40.23689374,
       61.83020602, 79.94481794, 75.01365839, 54.63510555, 34.21206098,
       90.54671411, 95.86155507, 85.40451939, 40.45755098, 32.57720017,
       82.22666158, 68.46852179, 52.10797973, 80.366756  , 39.53833914,
       52.34800399, 76.97878373, 38.7858038 , 91.5649745 , 99.31500881,
       55.34001756, 66.74671857, 67.37202755, 89.84580671, 72.34649423,
       50.4581598 , 62.27101367, 64.17698887, 94.83450672, 77.19303493,
       34.18364003, 66.56089447, 74.24869137, 82.30705337, 78.63542435,
       32.72283304, 75.47770201, 33.91550011, 89.67677575, 57.23870632,
       84.43281996, 42.26170081, 49.07256322, 44.66826172, 97.77159928,
       51.04775177])

In [84]:
x2 = X_train[:,1]

In [85]:
x2

array([60.999031  , 38.80067034, 92.92713789, 68.86157272, 49.59297387,
       75.85844831, 43.89499752, 47.02051395, 65.56892161, 46.85629026,
       75.34437644, 89.20735014, 46.67857411, 56.30804622, 41.57341523,
       56.31637178, 87.50879176, 78.45356225, 78.02469282, 71.16774802,
       50.25610789, 74.16311935, 30.60326323, 52.21388588, 44.2095286 ,
       43.39060181, 38.22527806, 57.05198398, 97.53518549, 95.59854761,
       42.71987854, 85.5943071 , 63.12762377, 90.9601479 , 76.03681085,
       60.76950526, 47.57596365, 64.99568096, 88.69629255, 68.77540947,
       64.93193801, 60.99139403, 42.83843832, 45.35828361, 96.22759297,
       75.80985953, 69.95445795, 80.90806059, 45.6943068 , 70.4582    ,
       75.23772034, 41.09209808, 69.82457123, 76.4819633 , 96.64742717,
       43.30717306, 90.424539  , 98.86943574, 65.79936593, 59.51428198,
       43.53339331, 87.10385094, 51.88321182, 66.45008615, 86.72782233,
       45.82270146])

In [86]:
b0=0.0
b1=0.0
b2=0.0
y = b0 + b1*x1 + b2*x2
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [87]:
prediction = 1/(1+np.exp(-y))
print(np.round(prediction))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [88]:
print(Y_train) #predicted and training values are different

[[1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]]


In [95]:
alpha = 0.3
epochs = 1000
x=1
for epoch in range(epochs):
    prediction = 1/(1+np.exp(-y))
    # Update b0,b1,b2
    b0 = b0 + alpha * (y - prediction) * prediction * (1-prediction) * x
    b1 = b1 + alpha * (y - prediction) * prediction * (1-prediction) * x1
    b2 = b2 + alpha * (y - prediction) * prediction * (1-prediction) * x2

In [96]:
y_final = b0 + b1*x1 + b2*x2
prediction = 1/(1+np.exp(-y_final))
print(np.round(prediction))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [97]:
print(Y_train)

[[1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]]
